### ISSUE TITLE
2020 Scouting System Planning

### ISSUE THREAD

**Issue by yuliu2016** [Team865/Android-Scouting-App#5]
This is an ongoing list of tasks to be completed for the 2020 version of the scouting app. The codebase needs to be completed by February 14th, 2020 (3 weeks before the first competition). Data analysis is not included in this list as it's a lot more flexible.

# Scouting App Features and Enhancements
This section includes enhancements to the scouting app compared with last season

### UI/UX
- [x] Create scouting layouts for 2020
  - [x] Autonomous Screen #16
  - [x] Teleop Screen #16
  - [x] Endgame Screen #16
  - [x] Super Scouting #38
  - [x] Add Tags #36
- [x] ~Explore changing the app icon~ Deferred
- [x] ~Add a `SliderField` with discrete values~ Deferred
  - [x] ~Explore continuous values~ not possible due to limitations of the V6 Encoder
- [x] Add settings item for team number @LocPham2003 #6 #13
  - [x] Validate team number
  - [x] Remember number
- [x] Add settings item for event @LocPham2003 #6 #13
  - [x] Show events with the team in it from TBA
  - [x] ~Add an override-with-key option~
  - [x] Remember event key
- [x] ~Explore merging already-scouted entries with the match schedule~ Rejected
- [x] ~Explore deleting a scouted entry~ ~Rejected~
- [x] Enable super-scouting board #11
- [x] ~Explore adding a popup screen for buttons that are not often used~ Rejected for tags in comments
- [x] ~Explore adding a section of the screen that doesn't move~ Rejected
- [x] Integrate match schedule into the main activity if the event key preference exists #19
- [x] Highlight team-in-event on the match schedule #27 
- [x] Add event selection activity

### Data Backend
- [x] Implement V6 Encoding 
  - [x] Explore tracking precision to 10th of a second
  - [x] Explore tracking precision to 100th of a second
  - [x] ~Explore~ Implement removing the space in the scout name
  - [x] ~Explore~ Implement ~removing the event name~ Simplifying the event name
  - [x] ~Explore~ remove the undo count
  - [x] ~Explore~ Implement optimizing index lookup with a binary search
  - [x] Add a `displayName` property to `Board`, and remove `board_choice` string resource
  - [x] Change time tracker from `Int` to `Double`
  - [x] Reimplement the `focused` function with a modified binary search, which returns true if time is "close enough"
- [x] Create a specification format in JSON so that the setup (scouting metrics, screens, etc.) can be changed without changing code
  - [x] Design the scouting screen template format
  - [x] Implement a parser and serializer #16
  - [x] Implement reading from and writing to files #16
  - [x] ~Explore Opening the file using a file extension~ Rejected
  - [x] ~Explore adding TBA key and team number~ Rejected
  - [x] ~Explore adding match schedule~ Rejected
  - [x] Remove hard-coded  `exampleBoardfile` #16
- [x] ~Explore adding condensed data tracking for `ButtonField`~ Rejected. Timetamp is important.
- [x] Add fetching match schedules from TBA #19
- [x] Explore the ability to cache TBA match schedules #7 and #19
- [x] Explore the ability to remember previously scouted matches after the app is closed
  - [x] ~Add settings option to clear the history~ Rejected for automatic hiding on event change

### App Architecture
- [x] Remove 2018 app (v4) from the codebase, including classes and resources
- [x] Integrate the Toggle Switch Button library directly in the codebase
- [x] Integrate the Kotlin TBA library in the codebase #7
  - [x] Replace direct calls of `URL.openConnection` with the library functions #19
- [x] Setup a CI workflow with GitHub Actions
  - [x] Explore enforcing branching/pull requests
  - [x] ~Explore automatic publishing~
  - [x] ~Explore linting~
- [x] Set up a unit testing framework #8 

# Alpha Release Change List
This section includes issues/bugs that are fixed as they are found through the development of 2020.1.0-alpha

### Regressions
- [x] Fix a regression caused by a `getString` call to a nonexisting string resource, making the Settings activity crash when started #9
- [x] Fix a regression caused by a potential null-receiver on the shared preferences #9 
- [x] Revert binary search algorithm causing infinite loops 
- [x] Fix a regression caused by attempting to format a double string, by adding integer conversion to the displayed time 
- [x] Fix a null pointer exception trying to access the vibrator before the context is fully created 
- [x] Fix an extra tab state update caused by a `Handler` method call in `SwitchField` 
- [x] Fix a string encoder regression that produces duplicate characters in each data point, which is caused by different bitwise operator precedence between Java and Kotlin 
- [x] Fix a regression on the `getNextIndex` function always returning 1 when the time is 0
- [x] Fix a regression caused by `getRelativeTime` returning match time field 
- [x] Fix a regression caused by the `data` class of `TemplateField` overriding `equals` #29

### Code Quality
- [x] Condense root package into less number of files 
- [x] Write unit tests for the V6 Encoder
- [x] Write V6 changes in the code docs
- [x] Refactor `.v5` out of the codebase #10 
- [x] Move `currentTime` out of the scouting activity interface as it's only used in the implementation
- [x] Remove `ManagedPreferences`
- [x] Remove `handler` from the scouting activity interface
- [x] Refactor `relativeTime` into a function instead of property
- [x] Refactor `ScoutingActivity`'s UI components from `lateinit`s to getters
- [x] ScoutingActivity: Move intent processing into local scope
- [x] Move board names from string resources to `Board`
- [x] Refactor `MainActivity`'s UI components from `lateinit`s to getters #18
- [x] Reorganize `MainActivity` into more functions #18
- [x] Move `validateName` to a top-level file #18
- [x] Fix deprecated call to `FragmentPagerAdapter` #24
- [x] Refactor EventInfo into new package #23
- [x] Remove unnecessary `data` modifier in classes #29 
- [x] Change EntryItemState into two properties: `isComplete` and `isScheduled` #29
- [x] Rename `EntryItem` to `EntryInMatch` #29

### UI/UX
- [x] ~Add a settings option to~ relax the restriction on scout name by allowing multiple initials after the first name #18
- [x] Fix crash if permission is not granted in `MainActivity` #18
- [x] Fix hardcoded colours for `EntryListAdapter` #14
- [x] Simplify vibration by making it a function in `BaseScoutingActivity` #11
- [x] ~Explore improving the event selector box to be non-scrolling~ Deferred
- [x] `QRCodeFragment`: Do not update unless data points or comments change #11 
- [x] ~Hide non-scouted entries with eye toggle~ Remove eye toggle #18
- [x] Remove "qm" qualifier from UI, and add M to keep consistency #18
- [x] ~Update~ Remove "eye" icon ~to better reflect purpose~ due to being unused #18
- [x] Make more space for event name by making the toolbar text smaller #20 
- [x] Remove bold font in the app to make UI more consistent #20
- [x] Change "add new entry" font size to match the rest of the UI #27
- [x] Remove separate color for `Added` entry state #27
- [x] Swap outer and inner buttons on the two screens @LocPham2003 #28
- [x] Event selection: Exit to main instead of settings #30
- [x] Replace schedule searching with result intent #29
- [x] Add `periodicUpdate` function to avoid self-referencing `Runnable` #29
- [x] `ScoutingActivity`: Remove old hidden feature `timerIsCountingUp` on title banner #29
- [x] `EntryInMatch`: Add CSV converter #29
- [x] Layout: Remove the Inner button

### Data Backend
- [x] Remove `isTiming` property from entry implementation due to always `true` #11
- [x] `DataPoint`: Stop Implementing `Iterable<Byte>` #11
- [x] `BaseScoutingActivity.relativeTime`: Use `Double` to avoid conversion in fields #11
- [x] Remove incorrect return of `low - 1` in `getNextIndex` #11
- [x] Rename `focused` to `isFocused` for clarity #11
- [x] Update `Boardfile.json` with serializer #16
- [x] Separate `eventKey`, `eventName`, and `matchSchedule` from Boardfile into `EventInfo` #16
- [x] Set up build config script to hide TBA key #15
- [x] `FieldType`: Rename `Toggle` to `MultiToggle` for clarity #16
- [x] Remove `exampleMatchSchedule` #19
- [x] Boardfile: Separate version into year and revision #22 
- [x] Pass entire entry as an intent to `ScoutingActivity` #29
- [x] `ScoutingActivity`: Pause timer when the activity pauses #31
- [x] `ScoutingActivity`: Keep the screen on while scouting #31
- [x] Distinguish buttons with the same name between auto and tele

### App Architecture
- [x] Update code dependencies
  - [x] Kotlin 1.3.60
  - [x] Android Tools 3.5.3
  - [x] ~Android 10 Target SDK~
  - [x] AndroidX artifacts for `appcompat`
- [x] Fix an issue caused by the absence of `local.properties` on CI builds
- [x] Update `.gitignore` to exclude `gradle.properties`

# Beta Release Change List
This section includes issues/bugs that are fixed as they are found through the development of 2020.1.0-beta

### Regressions
- [x] Fix undo not showing up on QR code scanner if there is only one data point #40
- [x] **Critical** Fix inverted value on Checkbox and Switch #34
- [x] Fix a regression where tapping on the bounding box of a `CheckboxField` inverts it #36

### UI/UX
- [x] Add ripple effect on `ButtonField`, `SwitchField` and `CheckboxField` to make it consistent with other buttons #34
- [x] Fix colors in ripple_transparent #34
- [x] Fix activity crash when nothing is entered in an unscheduled match #39
- [x] Add tags in the comment text box #36
- [x] Add retainInstance to tab fragments #37 
- [x] Add team number templates #37
- [x] Add team number templates for tags #38
- [x] Add Switch Lite #38
- [x] Add team number templates for MultiToggle #38
- [x] Add settings hint in `MainActivity` #39
- [x] Lift restriction on adding unscheduled matchs while in a super scouting board #39
- [x] Add option to delete a scouted entry #39
- [x] Switch Lite: Don't disable when not in timed scouting #40

### Data Backend
- [x] Change field data to zero-indexed #34
- [x] Add `RelativeBoard` for team templates #37
- [x] Add match schedule to super scouting encoder #38
- [x] Fix the blue alliance instance always using cache-first #40

### Code Quality
- [x] Extract inline strings into resources #36
- [x] Remove boardfile from `BaseScoutingActivity` #37
- [x] Remove `updateTabStates` from `BaseScoutingActivity` #37
- [x] Clean up `boardfile`, `getScreens`, and `pagerAdapter` in `ScoutingActivity` #37

# Final Change List
This section includes issues/bugs that are fixed as they are found through the development of 2020.1.0 final

- [x] Rename Field Areas and re-word some buttons in the layout #41
- [x] Remove generic options field in JSON #41
- [x] Remove and Serializer.kt #41 
- [x] Super Scouting: Fix match not saved when start timer is not clicked #42
- [x] QRCodeFragment: Fix encoded text not showing up #43 
- [x] Auto: Change intake buttons to reflect zones #44
- [x] Add updateAdjacentTabState call when additional info is edited #45

# Desktop Tools
This section includes the development of desktop tools for the scouting system

### WARP7 Scouting Scan Tool Features
- [x] Implement new QR Code Scanner
  - [x] Multiple cameras, with the ability to refresh
  - [x] Image flipping
  - [x] Image resizing to screen
  - [x] AutoSave
  - [x] Open saved data
  - [x] Skip incompatible lines in the save file
  - [x] Sort matches
  - [x] Scout Stats
  - [x] Duplicate Detection
  - [x] Missing Entries Detection
- [x] Set up a repository in the team GitHub account [repo link](https://github.com/Team865/Scouting-App-Scanner)
  - [x] Port the code as a separate Gradle build
  - [x] Publish 2020.1.0 (initial release)
  - [x] Publish 2020.1.1 (bug fixes)
  - [x] Publish 2020.2.0 (v6 encoding, super scouts)
- [x] Package Scanner as stand-alone installer
- [x] Update to Encoding V6, potentially changing event, scout name, and undo
- [x] ~Explore adding CSS into the application~
- [x] ~Add an "About" section~
- [x] ~Explore fullscreen shortcuts~

### WARP7 Scouting Scan Tool Bugs
- [x] Change app icon from PNG to ICO 
- [x] Change ICO size to maximum 
- [x] Add correct icon to the window 
- [x] Add ownership to child windows in the main stage 
- [x] Change application title 
- [x] Change `confirm` function from `Alert` to `Dialog<ButtonType>` 
- [x] Refactor `Cells.kt` into separate classes 
- [x] ~Fix "Open File" not showing entries~ Move Java classes out of Kotlin source folder 
- [x] Remove restriction on super scouts in Missising Entries
- [x] Add `M` prefix to scout stats and table
- [x] Change title to include app version

### Raw Data Processing
- [x] Implement the V6 Decoder in Python
- [x] Implement board file lookup in Python
- [x] Implement basic processing @EvanBialo

**Comment by yuliu2016** [comment]
## Bug Recovery
This is an ongoing list of bugs that need to be fixed
